/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2023-05-07 19:22:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.View;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>Add Product</title>\n");
      out.write("\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://unpkg.com/boxicons@latest/css/boxicons.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/CSS/navb.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/CSS/AddProduct.css\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Mochiy+Pop+One&family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\" integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t \n");
      out.write("\t<header>\n");
      out.write("        <span class=\"logo\">Hamro&nbsp;Pasal</span>\n");
      out.write("        <div class=\"right\">\n");
      out.write("            <select name=\"category\" id=\"category\">\n");
      out.write("                <option value=\"all\">Categories</option>\n");
      out.write("                <option value=\"shirt\">Shirt</option>\n");
      out.write("                <option value=\"pants\">Pants</option>\n");
      out.write("                <option value=\"shoes\">Shoes</option>\n");
      out.write("            </select>\n");
      out.write("            <form action=\"\" class=\"search-bar\">\n");
      out.write("                <input type=\"text\" class=\"search-field\" placeholder=\"Search this Website\">\n");
      out.write("                <input type=\"submit\" id=\"search\">\n");
      out.write("                <label for=\"search\"><i class='bx bx-search-alt-2'></i></label>\n");
      out.write("            </form>\n");
      out.write("            <div class=\"icons\">\n");
      out.write("                <div class=\"cart\" onclick=\"cartClicked()\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Images/shopping-cart.png\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"profile\" onclick=\"profileClicked()\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Images/user.png\" alt=\"\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"profile-section\">\n");
      out.write("        \t<div class=\"top\">\n");
      out.write("                <h1>User Profile</h1>\n");
      out.write("                <i class='bx bxl-xing' onclick=\"profileClicked()\"></i>\n");
      out.write("            </div>\n");
      out.write("        \t");
 String email = null;
        	if(session.getAttribute("loggedInId") == null){ 
        	
      out.write("\n");
      out.write("            \t<div class=\"middle\">\n");
      out.write("\t                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AdminLogin.jsp\">Login as Admin</a>\n");
      out.write("                \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/Login.jsp\">Login as User</a>\n");
      out.write("        \t");
} else{
        		email = session.getAttribute("loggedInId").toString();
        	
      out.write("\n");
      out.write("        \t\t<h1>You are Logged In as ");
      out.print( email );
      out.write("</h1>\n");
      out.write("        \t\t");
if(session.getAttribute("adminEmail") != null){
      out.write("\n");
      out.write("        \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Return to Home</a><br/>\n");
      out.write("        \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AdminPage.jsp\">Admin Page</a><br/>\n");
      out.write("        \t\t");
}
      out.write("\n");
      out.write("        \t\t\n");
      out.write("        \t\t");
if(session.getAttribute("adminEmail") == null && session.getAttribute("loggedInId") != null){
      out.write("\n");
      out.write("         \t\t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editProfile?email=");
      out.print(email);
      out.write(" class=\"edit-profile-btn\">Edit Profile</a><br/>\n");
      out.write(" \n");
      out.write("        \t\t");
}
      out.write("\n");
      out.write("        \t\t\n");
      out.write("        \t\t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\">Log Out</a>\n");
      out.write("        \t");
} 
      out.write("\n");
      out.write("        \t</div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"cart-section\">\n");
      out.write("        \t<div class=\"top\">\n");
      out.write("                <h1>Cart Items</h1>\n");
      out.write("                <i class='bx bxl-xing' onclick=\"profileClicked()\"></i>\n");
      out.write("            </div>\n");
      out.write("        \t<div class=\"middle\" id=\"middle\">\n");
      out.write("\t\t\t\t\n");
      out.write("            </div>\n");
      out.write("        \t<div class=\"lower\">\n");
      out.write("        \t\t\n");
      out.write("        \t</div>\n");
      out.write("        </div>\n");
      out.write("        <script>\n");
      out.write("            const profileClicked = () =>{\n");
      out.write("                const btn = document.querySelector(\".profile\")\n");
      out.write("                const mainDiv = document.querySelector(\".profile-section\")\n");
      out.write("                const cross = document.querySelector(\".profile-section .top i\")\n");
      out.write("                btn.addEventListener(\"click\", ()=>{\n");
      out.write("                    mainDiv.classList.add(\"active\");\n");
      out.write("                })\n");
      out.write("                cross.addEventListener(\"click\", ()=>{\n");
      out.write("                    mainDiv.classList.remove(\"active\");\n");
      out.write("                })\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            const cartClicked = () =>{\n");
      out.write("            \t");
if(session.getAttribute("adminEmail") == null && session.getAttribute("loggedInId") != null){ 
      out.write("\n");
      out.write("                const btn = document.querySelector(\".cart\")\n");
      out.write("                const mainDiv = document.querySelector(\".cart-section\")\n");
      out.write("                const cross = document.querySelector(\".cart-section .top i\")\n");
      out.write("                btn.addEventListener(\"click\", ()=>{\n");
      out.write("                    mainDiv.classList.add(\"active\");\n");
      out.write("                })\n");
      out.write("                cross.addEventListener(\"click\", ()=>{\n");
      out.write("                    mainDiv.classList.remove(\"active\");\n");
      out.write("                })\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                let cartDisplay = document.getElementById(\"middle\");\n");
      out.write("\t\t\t\tlet totalPriceDisp = document.querySelector(\".lower .total-price\");\n");
      out.write("                // Create an empty string to store the HTML content\n");
      out.write("                let cartHtml = \"\";\n");
      out.write("\t\t\t\tlet totalPrice = 0;\n");
      out.write("                // Loop through the cart object and generate HTML for each item\n");
      out.write("                cartItems.forEach((item) => {\n");
      out.write("                  cartHtml += `\n");
      out.write("                \t<div class=\"item\">\n");
      out.write("  \t\t\t\t\t\t<img src=/HamroPasal/Images/`+item.image+`?v=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${time}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/>\n");
      out.write("  \t\t\t\t\t\t<span>\n");
      out.write("  \t\t\t\t\t\t\t<h3>`+item.name+`</h3>\n");
      out.write("\t  \t\t\t\t\t\t<p>Price: Rs. `+item.price+`</p>\n");
      out.write("\t  \t\t\t\t\t</span>\n");
      out.write("  \t\t\t\t\t</div>\n");
      out.write("                  `;\n");
      out.write("                  totalPrice += parseInt(item.price);\n");
      out.write("                })\n");
      out.write("                // Set the innerHTML of the cart display element to the generated HTML content\n");
      out.write("                cartDisplay.innerHTML = cartHtml;\n");
      out.write("                totalPriceDisp.innerText = totalPrice;\n");
      out.write("                ");
}else{
      out.write("\n");
      out.write("                \twindow.location.href = \"./View/Login.jsp\"\n");
      out.write("                ");
}
      out.write("\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("        </script>\n");
      out.write("    </header>\n");
      out.write("    <hr>\n");
      out.write("    <section class=\"admin-header\" style=\"margin:10px 0\">\n");
      out.write("    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AdminPage.jsp\">Dashboard</a>\n");
      out.write("    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manageusers\">Manage Users</a>\n");
      out.write("    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/View/AddProduct.jsp\">Add Product</a>\n");
      out.write("    \t<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/manageproducts\">Edit Product</a>\n");
      out.write("    </section>\n");
      out.write("    \n");
      out.write("    <div class=\"add-product-form\">\n");
      out.write("        <form action=\"../addproduct\" method=\"post\" enctype=\"multipart/form-data\">\n");
      out.write("            <div class=\"top\">\n");
      out.write("                <div class=\"left2\">\n");
      out.write("                    <span>\n");
      out.write("                        <label for=\"prod-name\">Product Name:</label><br>\n");
      out.write("                        <input type=\"text\" placeholder=\"Product Name\" id=\"prod-name\" name=\"product_name\">\n");
      out.write("                    </span>\n");
      out.write("    \n");
      out.write("                    <span>\n");
      out.write("                        <label for=\"prod-price\">Product Price:</label><br>\n");
      out.write("                        <input type=\"number\" placeholder=\"Product Price\" id=\"prod-price\" name='product_price'>\n");
      out.write("                    </span>\n");
      out.write("    \n");
      out.write("                    <span>\n");
      out.write("                        <label for=\"prod-quantity\">Product Quantity:</label><br>\n");
      out.write("                        <input type=\"number\" placeholder=\"Product Quantity\" id=\"prod-quantity\" name='product_quantity'>\n");
      out.write("                    </span>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"right2\">\n");
      out.write("                    <label for=\"prod-image\" class=\"img-section\">\n");
      out.write("                        <img src=\"\" alt=\"\" class=\"showImage\">\n");
      out.write("                    </label>\n");
      out.write("                    <input type=\"file\" id = \"prod-image file\" name=\"image\" class=\"imageChooser\" value =\"profile-eg.png\" onchange=\"onImageChange()\"/>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"bottom\">\n");
      out.write("                <button type=\"submit\" value=\"Add Product\">Add Product</button>\n");
      out.write("                <a href=\"#\">Cancle</a>\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    <script>\n");
      out.write("\t\tfunction onImageChange(){\n");
      out.write("\t\t\tvar imageChooser = document.querySelector(\".imageChooser\");\n");
      out.write("\t\t\tvar showImage = document.querySelector(\".showImage\");\n");
      out.write("\t\t\tshowImage.src = URL.createObjectURL(imageChooser.files[0]);\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
